name: Build for Android

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: Limit heap space
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm start
      

      - name: Install IONIC
        run: npm install -g @ionic/cli

      - name: Install APP dependencies
        run: npm install

      - name: Build Ionic APP
        run: ionic build --verbose

      - name: Generate Android  files
        run: ionic capacitor copy android

      - name: Build Dev Version Android
        run: ionic capacitor build android

      - name: Build Release version Android
        run: ionic capacitor build android --release --prod 

      
      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: apk/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: apk/app.aab
