name: Build for Android

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Test increment var
        env:
          build_s: ${GITHUB_REF#refs/*/}
          build_n: ${build_s:5:3}
        run: echo "The build string is $build_s \nThe build number is $build_n"
