name: Build for Android

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Test increment var
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
