name: Build for Android

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Build String
        run: echo "BUILD_STRING=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Number
        run: echo "BUILD_NUMBER=${BUILD_STRING:5:3}" >> $GITHUB_ENV

      - name: Display numbers
        run: echo "Build string is ${{env.BUILD_STRING}} \nBuild number is ${{env.BUILD_NUMBER}}"

