name: Build for Android

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x      

      - name: Install IONIC
        run: npm install -g @ionic/cli

      - name: Install APP dependencies
        run: npm install
        
      - name: Build Ionic APP
        env:
          CI: ""
        run: ionic --max_old_space_size=2048 build

      - name: Generate Android  files
        env:
          CI: ""
        run: ionic capacitor copy android

      - name: Build Dev Version Android
        env:
          CI: ""
        run: ionic capacitor build android

      - name: Build Release version Android
        env:
          CI: ""
        run: ionic capacitor build android --release --prod 

      - name: Generate the debug APK
        working-directory: ./android/
        run: ./gradlew assemble
      
      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle
  
      - name: debug again
        run:  pwd ./android/app/build/outputs/bundle/release/
  
      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev
          path: ./android/app/build/outputs/bundle/release/*.aab

      - name: Upload release bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ./android/app/build/outputs/apk/debug/*.apk
