name: Build for Android

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Test increment var
        run: echo "${{ github.run_number }}"